### ISSUE TITLE
Error in cargo build

### ISSUE THREAD

**Issue by aniketpr01** [Phala-Network/zk-sgx-attester#1]
Trying to build with Rust stable version 1.82 and got these error log

OS: Mac M1

```
rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)

cargo build
warning: `/Users/aniket.p/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/aniket.p/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
error: invalid inline table
expected `}`
 --> ../../../../.cargo/git/checkouts/risc0-7d6ab9951628e5b1/7f73166/templates/rust-starter/host/Cargo.toml:8:16
  |
8 | risc0-zkvm = { {{ risc0_zkvm }} }
  |                ^
  |
error: invalid inline table
expected `}`
 --> ../../../../.cargo/git/checkouts/risc0-7d6ab9951628e5b1/7f73166/templates/rust-starter/methods/Cargo.toml:7:17
  |
7 | risc0-build = { {{ risc0_build }} }
  |                 ^
  |
error: invalid inline table
expected `}`
 --> ../../../../.cargo/git/checkouts/risc0-7d6ab9951628e5b1/7f73166/templates/rust-starter/methods/guest/Cargo.toml:2:9
  |
2 | name = {{ guest_package_name }}
  |         ^
  |
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12   
   .
   .
   .
   Compiling risc0-core v0.21.0-alpha.1 (https://github.com/risc0/risc0?rev=7f731662#7f731662)
   Compiling Inflector v0.11.4
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/aniket.p/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

   Compiling bs58 v0.5.0
   Compiling sha1 v0.10.6
   Compiling ripemd v0.1.3
   Compiling pin-project-internal v1.1.4
   Compiling tracing-subscriber v0.2.25
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```
